### ISSUE TITLE
SKU305030059 : Faulty wiring Drain and Source

### ISSUE THREAD

**Issue by hisashin** [Seeed-Studio/OPL_Eagle_Library#1]
I found out why DIP MOSFET SKU305030059 in my last PCBA orders (171009101001, 170619161000) doesn't work.
Seeed-Transistor/DIP-MOSFET-N-CH-100V-9.7A-IRF520NPBF(TO-220AB) is wrong. 

In datasheet, Pin2&4 is Drain and Pin3 is Source.
https://statics3.seeedstudio.com/images/opl/datasheet/305030059.pdf
But in latest library, Pin2&4 is Source and Pin3 is Drain.

By switching these legs, it worked. Please check it and hope that to be fixed soon.

Shingo

**Comment by Huangw0107** [comment]
Hi ，hisashin，I just checked it. The transistor has been modified.Thank you very much。

**Comment by hisashin** [comment]
Great!
